### ISSUE TITLE
BUG REPORT!

### ISSUE THREAD

**Issue by zeroninefourfour** [PapaSnags/Discord-BOT-Dashboard#4]
NEW BUG
when i use help command it show this and exit
```
/home/runner/HelpfulJovialSource/node_modules/discord.js/src/structures/MessageEmbed.js:450
      .flat(2)
       ^

TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Object.exports.run (/home/runner/HelpfulJovialSource/commands/help.js:15:18)
    at module.exports (/home/runner/HelpfulJovialSource/events/message.js:19:9)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/HelpfulJovialSource/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
exit status 1
```

**Comment by zeroninefourfour** [comment]
all command

**Comment by LachlanDev** [comment]
Not a bug update the Node.JS version
First: run this command **npm install -g n**
Seccond: **n latest**
